# Generated by Django 3.1.5 on 2021-05-05 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lista_cliente',
            name='tipo_Documento',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
