# Generated by Django 3.1.4 on 2021-05-12 23:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carsapp', '0002_lista_cliente_tipo_documento'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='cedula_Emp',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='carsapp.empleados'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('1', 'Administrador'), ('2', 'Recepcionista'), ('3', 'Empleado')], default='3', max_length=1),
        ),
    ]
