# Generated by Django 3.1.4 on 2021-05-16 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carsapp', '0003_auto_20210512_1852'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='nombre_usuario',
            new_name='usuario',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='nombre',
        ),
    ]
