# Generated by Django 3.1.4 on 2021-05-16 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carsapp', '0004_auto_20210516_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('Administrador', 'Administrador'), ('Recepcionista', 'Recepcionista'), ('Empleado', 'Empleado')], default='3', max_length=15),
        ),
    ]
