# Generated by Django 3.2.3 on 2021-05-24 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carsapp', '0005_auto_20210516_1416'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id_proveedor', models.AutoField(primary_key=True, serialize=False)),
                ('nit', models.CharField(max_length=30)),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.AlterField(
            model_name='inventario',
            name='provedor',
            field=models.ForeignKey(default='Desconocido', on_delete=django.db.models.deletion.DO_NOTHING, to='carsapp.proveedor'),
        ),
    ]
