# Generated by Django 3.2.3 on 2021-05-25 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carsapp', '0006_auto_20210524_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventario',
            name='imagen',
            field=models.ImageField(null=True, upload_to='productos/'),
        ),
    ]
