# Generated by Django 3.1.4 on 2021-05-25 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carsapp', '0007_inventario_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='id_Cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='carsapp.lista_cliente'),
        ),
    ]
