# Generated by Django 3.1.4 on 2021-05-30 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carsapp', '0008_vehiculo_id_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='RevisionVehiculo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estadoProceso', models.CharField(blank=True, max_length=30, null=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carsapp.empleados')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carsapp.vehiculo')),
            ],
        ),
    ]
