# Generated by Django 3.1.4 on 2021-05-30 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carsapp', '0010_auto_20210530_1445'),
    ]

    operations = [
        migrations.RenameField(
            model_name='revisionvehiculo',
            old_name='empleado',
            new_name='cedula_Emp',
        ),
        migrations.RenameField(
            model_name='revisionvehiculo',
            old_name='vehiculo',
            new_name='id_vehi',
        ),
    ]
