# Generated by Django 3.1.4 on 2021-05-30 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carsapp', '0011_auto_20210530_1449'),
    ]

    operations = [
        migrations.RenameField(
            model_name='revisionvehiculo',
            old_name='cedula_Emp',
            new_name='empleado',
        ),
        migrations.RenameField(
            model_name='revisionvehiculo',
            old_name='id_vehi',
            new_name='vehiculo',
        ),
    ]
