# Generated by Django 3.1.4 on 2021-06-06 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carsapp', '0015_auto_20210531_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='imagen',
            field=models.ImageField(null=True, upload_to='productos'),
        ),
    ]
