# Generated by Django 3.1.4 on 2021-06-06 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carsapp', '0016_auto_20210606_0912'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehixservicio',
            old_name='id_VehiXServ',
            new_name='id',
        ),
        migrations.RemoveField(
            model_name='vehixservicio',
            name='id_Cuenta_ServicioFK',
        ),
        migrations.RemoveField(
            model_name='vehixservicio',
            name='id_ProductoFK',
        ),
        migrations.RemoveField(
            model_name='vehixservicio',
            name='id_Servicio_FK',
        ),
        migrations.AddField(
            model_name='vehixservicio',
            name='id_Servicio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='carsapp.servicios'),
        ),
        migrations.AddField(
            model_name='vehixservicio',
            name='id_Vehi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='carsapp.vehiculo'),
        ),
    ]
