# Generated by Django 3.1.4 on 2021-06-28 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carsapp', '0017_auto_20210606_1428'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetallesFacturas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_Producto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='carsapp.inventario')),
                ('id_Servicio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='carsapp.servicios')),
            ],
        ),
        migrations.CreateModel(
            name='Facturas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('totalAPagar', models.IntegerField()),
                ('id_Cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carsapp.lista_cliente')),
                ('id_Vehi', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='carsapp.vehiculo')),
            ],
        ),
        migrations.RemoveField(
            model_name='vehixcliente',
            name='idClienteFK',
        ),
        migrations.RemoveField(
            model_name='vehixcliente',
            name='idVehiFK',
        ),
        migrations.DeleteModel(
            name='Cuenta_Servicio',
        ),
        migrations.DeleteModel(
            name='VehiXCliente',
        ),
    ]
