# Generated by Django 3.1.4 on 2021-07-05 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carsapp', '0019_detallesfacturas_id_factura'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallesfacturas',
            name='cantidad_Producto',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='detallesfacturas',
            name='precio',
            field=models.IntegerField(null=True),
        ),
    ]
