# Generated by Django 3.1.4 on 2021-07-05 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carsapp', '0020_auto_20210705_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturas',
            name='fecha',
            field=models.DateTimeField(null=True, verbose_name='Fecha y hora del pedido'),
        ),
    ]
