# Generated by Django 3.1.4 on 2021-07-06 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carsapp', '0023_auto_20210705_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallesfacturas',
            name='precio',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='servicios',
            name='valor_Servicio',
            field=models.IntegerField(),
        ),
    ]
